#+title: About

This site is intended to be a journal of my personal creative projects, a place for me to share what I've been doing so that it might fuel my enthusiasm.

* Projects

** Game Development

*** Substratic Engine

I've been having a lot of fun developing a 2D game engine using functional programming patterns.  It's still too early to give a more thorough description of how it works, but I do intend to write more about it in this site as things progress.  In the meantime, you can check out the code at the [[https://github.com/substratic/engine][Substratic Engine repository]].

*** Crash The Stack

The first game project I'm planning to release using the Substratic Engine is called [[https://github.com/substratic/crash-the-stack][Crash The Stack]], a hacking game based loosely on PC mahjong game mechanics.  Much of the initial writing on this site will be to chronicle the development of this project.

** Music

I like to produce my own music but I rarely sit down to write anymore.  I'm hoping that my game projects will give me a good reason to get into a rhythm of producing music more frequently so that I can expand into making a full-length album.  You can check out a small sample of what I've made so far at my [[https://soundcloud.com/daviwil][SoundCloud page]].

** Video

I created a (now defunct) YouTube series called [[https://www.youtube.com/channel/UCAiiOTio8Yu69c3XnR7nQBQ][the_dev_aspect]] that gained a fair amount of views for the F# series I made in 2016.  One day I'll get back to making videos in some form.

** Computing Configuration

Everything I do is centered around the use of [[https://www.gnu.org/software/emacs/][GNU Emacs]] and the [[http://guix.gnu.org/][GNU Guix]] System distribution.  I've spent a lot of time creating a fully customized environment that is easily replicable across multiple machines.  You can read more about it at my [[https://github.com/daviwil/dotfiles][dotfiles repo]].  This site was written in Org Mode files and generated using Emacs.
